### PR TITLE
Bump to requests 2.30.0 and urllib3 2.0.1

### PR DESCRIPTION
**Pull request by pquentin**
Hello, urllib3 maintainer here :wave:

#343 and #345 failed because requests had not been updated yet. Let's try to update both

Closes #343

### CODE REVIEW

**Comment by hartwork** [comment]
PS: @pquentin fixing vcr.py to work with both urllib3 1.x and 2.x turns out pretty hard and will eat quite a bit of time. I'm not sure I'll find the time needed to make it work.

**Comment by pquentin** [comment]
Thanks for your own help fixing the ecosystem after we broke things! Would you have time to report why fixing vcrpy is hard and time consuming to help others build upon what you learned?

**Comment by hartwork** [comment]
@pquentin it's non-trivial in the sense that:
- some imports to connectionpool need to be changed to connection and some cannot, i.e. the ones with the pool classes
- so that situation requires a split of things and related changes
- there is monkey patching to all sorts of bundled urllib3 copies happening, not just plain urllib3, it's many places
- when mass patching all of that I now run into non-trivial errors now and that made me pause and reflect on how to continue economically.

Does that make sense?

**Comment by pquentin** [comment]
This makes a lot of sense, thank you!

**Pull request merged**
